### ISSUE TITLE
Document difference between erc721 reference implementation and framework implementation

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#386]
0xcert publishes two implementations of ERC-721.

* The reference implementation, cited in the standard, available at https://github.com/0xcert/ethereum-erc721
* The optimized implementation, used in the framework, available at https://github.com/0xcert/framework/tree/master/packages/0xcert-ethereum-erc721-contracts

Also, they have similar packages on NPM.

As current, there is much opportunity to confuse the two. More effort (naming? documentation?) should be used to differentiate and explain which is which.

**Comment by xpepermint** [comment]
@fulldecent regarding the name, I think it's ok because the readmes of the `0xcert-ethereum-erc721-contracts` and `ethereum-erc721` are different enough. The official https://github.com/0xcert/ethereum-erc721/ implementation has a very good readme, instructions and so on so a JS dev knows that he can use it.

I agree that we need to add some sentences in the 0xcert-ethereum-erc721-contracts readme. We'll do that. Thanks.

**Comment by MoMannn** [comment]
#454
