### ISSUE TITLE
xcert pause in undefined

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#396]
A pausing feature is defined in XcertPausable.setPause. But there is no corresponding documentation in https://docs.0xcert.org/api/ethereum.html#asset-ledger.

Which features are disabled when Xcerts are paused?

**Comment by MoMannn** [comment]
In the contract name pause is used since it is commonly used in smart contract development. But at the higher level aimed at javascript developer this is translated into two functions called [`enableTransfers`](https://docs.0xcert.org/api/ethereum.html#enabletransfers) and [`disabletransfers`](https://docs.0xcert.org/api/ethereum.html#disabletransfers).

The linkage of this can be seen in the `0xcert-ethereum-asset-ledger` package.

**Comment by fulldecent** [comment]
Good. I agree the contract naming and details can be abstracted in the TypeScript level.

Can notes please also be added in these locations:

* https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-xcert-contracts/src/contracts/ixcert-pausable.sol
* https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-xcert-contracts/src/contracts/xcert.sol#L83
* https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-xcert-contracts/src/contracts/xcert.sol#L146-L147

**Comment by MoMannn** [comment]
#439
