### ISSUE TITLE
order-gateway setProxy vulnerable to race condition

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#407]
The current setProxy implementation is vulnerable to a race condition against somebody executing an order.

Test case:

* Maker signs an order with proxy 1
* Admin changes proxy 1
* Taker executes order

**Comment by MoMannn** [comment]
The intended usage of setProxy was not to ever actually change a proxy to another. Its usage is meant for dynamic adding of new proxies of for being able to set proxy to 0 address in case of some problems. But I can see a problem with this not being enforced on chain. I suggest we change setProxy to addProxy and change so that proxy can only be added if 0 address and cannot be changed anymore. In case of problems you can always add another proxy and start using this + revoke orderGateway from the proxy side. What do you think? 

@fulldecent  @xpepermint

**Comment by fulldecent** [comment]
Sounds good. Just make sure you will not reuse proxies. Here is an implementation.

```
int[] proxies;

function addProxy(address proxy)
  proxies.push(proxy)

function removeProxy(uint index)
  proxies[index] = 0
```

**Comment by MoMannn** [comment]
#431
