### ISSUE TITLE
Explain how signing method will prevent replay attacks

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#435]
In the generic/metamask/http providers, there is an interface for signing messages (for transactions in general and for maker/taker).

It is cited that EIP-712 is used. But please explain if/how EIP-155 is used and whether this system is vulnerable to replay attacks:

1. On the same network (e.g. two separate SwapMarkets deployed)
1. On different networks (e.g. transaction on Ropsten replayed to Mainnet)

These two examples apply to SwapMarket, but please also explain for normal transactions (transferFrom).

**Comment by MoMannn** [comment]
Currently we only support `eth_sign` we are working on adding other signature types. `personal_sign` will probably be next. On the contracts itself we already have some logic to support other signatures but the framework itself does not. 

The answer for both point is the same and is: 
Every order has orderGateway contract address included. So if you deploy multiple OrderGateways it will only work on the one you sign the order for. This solved different network as well since they do not have the same contract addresses. 

As for normal transaction we do not support transaction signing at the moment: #268

**Comment by MoMannn** [comment]
#443
