### ISSUE TITLE
calculate imprint failed with datetime

### ISSUE THREAD

**Issue by qnguyen12** [0xcert/framework#547]
Here's my code
```
const schema22 = {
			"$schema":"https://testschema",
			"description": "test description",
			"title":"test title",
			"type": 'object',
			"properties": {
				"name": {
					"type": "string",
					"description": "some name"
				},
				"productionDate": {
					"type": "date-time",
					"description": "produced date"
				}
			}
		}
    
		const cert = new Cert({ schema: schema22 })
		const data = {
			"name": "jeans",
			"productionDate": new Date()
		}
		console.log('Data: ', data)
		var imprint =  await cert.imprint(data)
		console.log('Imprint: ', imprint)

		const proofs = await cert.notarize(data)
		console.log('Proofs: ', proofs)

		// calculate imprint
		const imprint_test = await cert.calculate(data, proofs)
		console.log('Imprint test: ', imprint_test)
```
calculate imprint is null if the schema has date-time type

**Comment by xpepermint** [comment]
Dates and other objects will always be converted to `string` so just change `date-time` to `string` for now and it will work. I'll check this issue in a few days.

**Comment by xpepermint** [comment]
@qnguyen12 I went fixing this and started by reading the docs. [Here](https://json-schema.org/understanding-json-schema/reference/type.html) it says that only `string`, `integer`, `number`, `object`, `array`, `boolean` and `null` types are supported by JSON Schema. What you are talking about are not types but string type [formats](https://json-schema.org/understanding-json-schema/reference/string.html#format).
Since this is not a valid bug I'm closing this issue.
