### ISSUE TITLE
Make proxy compatible with Gasless

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#606]
The new Dai allows ERC-20 transfers using off-chain signed messages. Sound familiar?

Implementation: https://github.com/makerdao/dss/blob/870d6fddb75090eb177290b1db4e255d2c31075e/src/dai.sol#L118

Writeup: https://medium.com/mosendo/gasless-by-mosendo-3030f5e99099

We should make our similar functionality work similar to this. Including checking that our function parameters are in the same order, etc.

**Comment by MoMannn** [comment]
I don't see the added value. We can create gas less transaction through actions gateway with much more added functionalities and we would like to use our infrastructure.  As such we also removed gas less transfer from ERC-20 and instead added auto approve to `TokenTransferProxy` to allow gas less transactions through actions gateway and since transfers will be limited to specific dapps.

**Comment by fulldecent** [comment]
Cool.
